# Generated by Django 5.2.7 on 2025-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(max_length=50, unique=True, verbose_name='Takip Numarası')),
                ('alici_adi', models.CharField(max_length=100, verbose_name='Alıcı Adı Soyadı')),
                ('kargo_icerigi', models.TextField(verbose_name='Kargo İçeriği')),
                ('durum', models.CharField(choices=[('Hazırlanıyor', 'Hazırlanıyor'), ('Yolda', 'Yolda'), ('Şubede', 'Şubede'), ('Teslim Edildi', 'Teslim Edildi')], default='Hazırlanıyor', max_length=20, verbose_name='Kargo Durumu')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
