# Generated by Django 5.2.7 on 2025-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('bolge', models.CharField(max_length=100)),
                ('durum', models.CharField(choices=[('Cevrimici', 'Çevrimiçi'), ('Yolda', 'Yolda')], max_length=20)),
                ('puan', models.FloatField(default=5.0)),
                ('foto_url', models.URLField(blank=True)),
            ],
        ),
    ]
