# Generated by Django 5.2.7 on 2025-12-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0002_kurye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurye',
            name='foto_url',
            field=models.URLField(blank=True, default='https://randomuser.me/api/portraits/men/1.jpg'),
        ),
    ]
