# Generated by Django 5.2.7 on 2026-01-09 09:54

import django.db.models.deletion
import takip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0003_alter_kurye_foto_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kargo',
            options={'verbose_name': 'Kargo', 'verbose_name_plural': 'Kargolar'},
        ),
        migrations.AlterModelOptions(
            name='kurye',
            options={'verbose_name': 'Kurye', 'verbose_name_plural': 'Kuryeler'},
        ),
        migrations.RenameField(
            model_name='kargo',
            old_name='alici_adi',
            new_name='alici_ad',
        ),
        migrations.AddField(
            model_name='kargo',
            name='kurye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kargolar', to='takip.kurye', verbose_name='Sorumlu Kurye'),
        ),
        migrations.AlterField(
            model_name='kargo',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='kargo',
            name='takip_no',
            field=models.CharField(default=takip.models.takip_no_olustur, editable=False, max_length=12, unique=True, verbose_name='Takip Numarası'),
        ),
        migrations.AlterField(
            model_name='kurye',
            name='bolge',
            field=models.CharField(max_length=100, verbose_name='Dağıtım Bölgesi'),
        ),
        migrations.AlterField(
            model_name='kurye',
            name='durum',
            field=models.CharField(choices=[('Cevrimici', 'Çevrimiçi'), ('Yolda', 'Yolda')], default='Cevrimici', max_length=20, verbose_name='Çalışma Durumu'),
        ),
        migrations.AlterField(
            model_name='kurye',
            name='foto_url',
            field=models.URLField(blank=True, default='https://randomuser.me/api/portraits/men/1.jpg', verbose_name='Fotoğraf URL'),
        ),
        migrations.AlterField(
            model_name='kurye',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Kurye Adı'),
        ),
        migrations.AlterField(
            model_name='kurye',
            name='puan',
            field=models.FloatField(default=5.0, verbose_name='Hizmet Puanı'),
        ),
    ]
